import { chromium } from '@playwright/test';
import { mkdirSync } from 'node:fs';

mkdirSync('test-results', { recursive: true });
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
page.on('response', response => { if (response.status() >= 400) errors.push(`${response.status()} ${response.url()}`); });
page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()); });
await page.goto('http://127.0.0.1:5173', { waitUntil: 'networkidle' });
await page.screenshot({ path: 'test-results/desktop.png' });
console.log('Sections:', await page.locator('main > section').count());
console.log('Desktop overflow:', await page.evaluate(() => document.documentElement.scrollWidth > innerWidth));
await page.locator('.theme-toggle-btn').click();
console.log('Theme:', await page.locator('html').getAttribute('data-theme'));
await page.locator('.hero-slide.active .nav-next').click();
console.log('Hero:', await page.locator('.hero-slide.active h1, .hero-slide.active h2').allTextContents());
await page.locator('.services-filter__tag[data-filter="ai-ml"]').click();
console.log('Filtered services:', await page.locator('.service-card:not([hidden])').count());
await page.setViewportSize({ width: 390, height: 844 });
await page.evaluate(() => scrollTo(0,0));
await page.screenshot({ path: 'test-results/mobile.png' });
console.log('Mobile overflow:', await page.evaluate(() => document.documentElement.scrollWidth > innerWidth));
await page.locator('.menu-toggle-btn').click();
console.log('Mobile menu:', await page.locator('body').getAttribute('class'));
await page.keyboard.press('Escape');
await page.locator('.contact-form-block input[name="name"]').fill('Preview Tester');
await page.locator('.contact-form-block input[name="phone"]').fill('5550100');
await page.locator('.contact-form-block input[name="email"]').fill('preview@example.com');
await page.locator('.contact-form-block select[name="industry"]').selectOption('Technology');
await page.locator('.contact-form-block select[name="budget"]').selectOption('N/A');
await page.locator('.contact-form-block textarea').fill('Local preview test');
await page.locator('.contact-form-block label').filter({ has: page.locator('input[name="agree"]') }).click();
await page.locator('.contact-form-block button[type="submit"]').click();
console.log('Contact preview:', await page.locator('.contact-form-block .local-form-status').textContent());
console.log('Missing images:', await page.locator('img').evaluateAll(images => images.filter(img => img.complete && !img.naturalWidth).map(img => img.src)));
console.log('Errors:', errors);
await browser.close();
if (errors.length) process.exitCode = 1;
