import CaseStudyNavigation from './CaseStudyNavigation';
export default function CaseContent() {
 return (
<section className={"post-section"}><div className={"container"}><div className={"flex post-section__flex"}><div className={"post-sidebar"}><div className={"post-sidebar__inner"}><div className={"post-index"} data-content={"#postContent .post-content__inner"}><CaseStudyNavigation />
</div>
</div>
</div>
<div id={"postContent"} className={"post-content post-content--case_study"}><div className={"post-content__inner typo"}><div className={"case-info card-block"}><h2 className={"case-info__title"} data-target={"0"} id={"about-the-client"}>{"About the client"}</h2>
<div className={"case-info__description typo"}><p><a href={"https://forethought.ai/"} target={"_blank"} rel={"nofollow noopener"}>{"Forethought"}</a>
{" is the most advanced agentic AI system for customer support, trained on your unique data and ready on day one. Powered by Autoflows technology, it autonomously handles complex issues end-to-end by reasoning, planning, following up, integrating APIs, and troubleshooting. With a multi-agent architecture, Forethought’s AI supports yI across channels, solving customer issues, assisting human agents, and uncovering valuable insights."}</p>
</div>
<div className={"tags case-info__tags"}>
<span className={"tag case-info__tag"}>{"AI & ML"}</span>

<span className={"tag case-info__tag"}>{"AI integration"}</span>

<span className={"tag case-info__tag"}>{"integrations"}</span>

<span className={"tag case-info__tag"}>{"Post-release support"}</span>

<span className={"tag case-info__tag"}>{"Project management"}</span>

<span className={"tag case-info__tag"}>{"QA/QC"}</span>

<span className={"tag case-info__tag"}>{"Web development"}</span>
</div>
</div>
<div className={"case-info__grid grid"}><div className={"grid-item"}><div className={"case-info__meta card-block"}>
<svg className={"icon"}>
<use href={"/assets/sprite.svg#icon-company"}></use>

</svg>
<span className={"case-info__meta-span"}>{"Martech"}</span>
</div>
</div>
<div className={"grid-item"}><div className={"case-info__meta card-block"}>
<svg className={"icon"}>
<use href={"/assets/sprite.svg#icon-location"}></use>

</svg>
<span className={"case-info__meta-span"}>{"USA"}</span>
</div>
</div>
</div>
<h2 id={"business-context"} className={"wp-block-heading has-large-font-size"} data-target={"1"}>{"Business context"}</h2>
<hr className={"wp-block-separator has-alpha-channel-opacity"} />
<p className={"wp-block-paragraph"}>{"Cooperation between me and "}<a href={"https://forethought.ai/"} target={"_blank"} rel={"noreferrer noopener nofollow"}>{"Forethought"}</a>
{" involved two of their projects for customer service automation: Assist and Discover."}</p>
<p className={"wp-block-paragraph"}>{"“Assist” aimed to make agents work faster, easier, and more efficiently, suggesting responses generated by "}{"AI"}
{" and "}{"machine learning"}
{", specifically "}{"large language models (LLMs"}
{"), during agent-customer conversations."}</p>
<p className={"wp-block-paragraph"}>{"“Discover” was tailored as a tool that optimizes workflows, tracks ROI and performance, and identifies and addresses gaps to resolve customer issues."}</p>
<section className={"grid-wrapper"} style={{}}><div className={"block-header"}><div className={"heading-with-button"}><div className={"heading-with-button__inner"}><h2 id={"challenges"} className={"block-title"} data-target={"2"}>{" Challenges"}</h2>
</div>
</div>
<hr className={"block-header__separator"} />

</div>
<div id={""} className={"grid-block grid typo grid--columns-2"} style={{"--cols": "2", "--cgap": ".5rem", "--rgap": ".5rem"}}><div id={""} className={"grid-item"}><div style={{"--pd": "24px", "--pm": "24px", "--phd": "24px", "--phm": "24px"}} className={"card-block img-top icn-top is-style-default-card wp-block-geniusee-card"}><div style={{"--is": "24px"}} className={"icon-block icon-block--align-left wp-block-geniusee-icon"}>
<svg className={"icon-block__icon"} width={"24"} height={"24"}><use href={"/assets/server-worldwide.svg#icon"}></use>
</svg>
</div>
<p className={"has-large-font-size wp-block-paragraph"}><strong>{"Integrating diverse services into a unified AI workflow"}</strong>
</p>
<p className={"has-default-font-size wp-block-paragraph"}>{"Forethought needed smooth alignment across the Chrome extension and multiple AI-powered support tools, ensuring consistent behavior and fast issue resolution across all customer-facing channels."}</p>
</div>
</div>
<div id={""} className={"grid-item"}><div style={{"--pd": "24px", "--pm": "24px", "--phd": "24px", "--phm": "24px"}} className={"card-block img-top icn-top is-style-default-card wp-block-geniusee-card"}><div style={{"--is": "24px"}} className={"icon-block icon-block--align-left wp-block-geniusee-icon"}>
<svg className={"icon-block__icon"} width={"24"} height={"24"}><use href={"/assets/users-03.svg#icon"}></use>
</svg>
</div>
<p className={"has-large-font-size wp-block-paragraph"}><strong>{"Delivering cross-platform compatibility for a broad client ecosystem"}</strong>
</p>
<p className={"has-default-font-size wp-block-paragraph"}>{"The solution had to work reliably for organizations using different software stacks, frameworks, and internal tools. So the client needed an effective solution covering a flexible, cross-platform layer that could serve a wide range of enterprise environments."}</p>
</div>
</div>
</div>
</section>
<p className={"has-small-font-size wp-block-paragraph"}></p>
<div className="project-solutions"><h2 id={"solutions-we-implemented"} className={"wp-block-heading has-large-font-size"} data-target={"3"}>{"Solutions I implemented"}</h2>
<hr className="solutions-divider" />

<h3 id={"project-management"} className={"wp-block-heading has-small-font-size"}><strong>{"Project management"}</strong>
</h3>
<p className={"wp-block-paragraph"}>{"I managed my development process according to quarterly goals and transitioned to the software development lifecycle using Scrum. A wisely chosen approach to project management allowed me to stage each sprint with an appropriate set of developed requirements and features. This ensured even distribution during all development phases."}</p>
<h4 id={"frontend-development"} className={"wp-block-heading has-small-font-size"}><strong>{"Frontend development "}</strong>
</h4>
<p className={"wp-block-paragraph"}>{"I chose React because of its open-source framework, which offers a wide range of free tools and libraries. Plus, React is one of the most popular frameworks for frontend development, as it assures smooth and easy system maintenance, making it quick and responsive. I also assisted in working with "}{"AWS services"}
{", e.g., Cognito for authorization."}</p>
<h4 id={"deep-integration-ecosystem"} className={"wp-block-heading has-small-font-size"}><strong><strong>{"Deep integration ecosystem"}</strong>
</strong>
</h4>
<p className={"wp-block-paragraph"}>{"I built reliable, scalable integrations with diverse enterprise systems, including CRMs, ticketing tools, and internal knowledge sources. I ensured AI agents operate seamlessly regardless of a client’s tech stack."}</p>
<h4 id={"quality-assurance"} className={"wp-block-heading has-small-font-size"}><strong>{"Quality assurance"}</strong>
</h4>
<p className={"wp-block-paragraph"}>{"I worked with Forethought to define quality standards and incorporate them throughout development. I supported code quality through reviews and unit tests, and collaborated on end-to-end testing to validate the functionality, reliability, and performance of the integrations."}</p>
<h3 id={"post-release-support"} className={"wp-block-heading has-small-font-size"}>{"5. Post-release support"}</h3>
<p className={"wp-block-paragraph"}>{"I continued to work closely with Forethought after the release, ensuring the platform operates reliably under real-world conditions. I handled issue resolution, removed legacy dependencies, and delivered ongoing updates. This includes implementing new features and enhancements driven by user behavior, product analytics, and evolving market demands."}</p>
</div>
<section id={""} className={"banner banner-content-block adaptive-simple-bg ta-left"} style={{}}><div className={"container"}><div className={"banner-content__inner"}><div className={"banner-content__background"}><img decoding={"async"} src={"/assets/forethought/contact-banner.png"} alt={"contact banner"} loading={"lazy"} title={"Forethought: Enterprise AI agents for customer support 2"} />
</div>
<div className={"banner-content__overlay"}></div>
<div className={"banner-content__main"}><h3 className={"banner-content__title size-medium"}>{"Build your next product with confidence"}</h3>
<div className={"banner-content__text"}><p>{"Work with me to build secure, scalable software through clear communication and dependable delivery."}</p>
</div>
<a className="btn btn-blue btn-large" href="/contact">Let's Talk <span aria-hidden="true">&#8599;</span></a>


</div>
</div>
</div>
</section>
<p className={"has-small-font-size wp-block-paragraph"}></p>
<section className={"grid-wrapper"} style={{}}><div className={"block-header"}><div className={"heading-with-button"}><div className={"heading-with-button__inner"}><h2 id={"features"} className={"block-title"} data-target={"4"}>{" Features"}</h2>
</div>
</div>
<hr className={"block-header__separator"} />

</div>
<div id={""} className={"grid-block grid typo grid--columns-2"} style={{"--cols": "2", "--cgap": ".5rem", "--rgap": ".5rem"}}><div id={""} className={"grid-item"}><div style={{"--pd": "24px", "--pm": "24px", "--phd": "24px", "--phm": "24px"}} className={"card-block img-top icn-top card-block--image wp-block-geniusee-card"}><figure className={"wp-block-image size-full card-image"}><img decoding={"async"} width={"2480"} height={"1600"} src={"/assets/forethought/Picture-8.png"} alt={"Picture 8"} className={"wp-image-6109"} title={"Forethought: Enterprise AI agents for customer support 3"} />
</figure>
<div className={"wp-block-group card-content is-layout-flow wp-block-group-is-layout-flow"}><h2 id={"chrome-extension"} className={"wp-block-heading"} data-target={"5"}>{"Chrome extension"}</h2>
<p className={"wp-block-paragraph"}>{"I delivered a Chrome extension for an AI-powered tool to enable support representatives to use one platform connected to many different services they use daily."}</p>
</div>
</div>
</div>
<div id={""} className={"grid-item"}><div style={{"--pd": "24px", "--pm": "24px", "--phd": "24px", "--phm": "24px"}} className={"card-block img-top icn-top card-block--image wp-block-geniusee-card"}><figure className={"wp-block-image size-full card-image"}><img decoding={"async"} width={"2480"} height={"1600"} src={"/assets/forethought/Picture-1-5.png"} alt={"Picture 1 5"} className={"wp-image-6110"} title={"Forethought: Enterprise AI agents for customer support 4"} />
</figure>
<div className={"wp-block-group card-content is-layout-flow wp-block-group-is-layout-flow"}><h4 id={"tasks-templates"} className={"wp-block-heading has-small-font-size"}>{"Tasks templates"}</h4>
<p className={"wp-block-paragraph"}>{"Admins may add tasks to Jira and assign them to service agents (certain customer support representatives) using templates. This allows me to work faster and avoid manual mistakes with self-service."}</p>
</div>
</div>
</div>
<div id={""} className={"grid-item"}><div style={{"--pd": "24px", "--pm": "24px", "--phd": "24px", "--phm": "24px"}} className={"card-block img-top icn-top card-block--image wp-block-geniusee-card"}><figure className={"wp-block-image size-full card-image"}><img loading={"lazy"} decoding={"async"} width={"2480"} height={"1600"} src={"/assets/forethought/Picture-2-4.png"} alt={"Picture 2 4"} className={"wp-image-6112"} title={"Forethought: Enterprise AI agents for customer support 5"} />
</figure>
<div className={"wp-block-group card-content is-layout-flow wp-block-group-is-layout-flow"}><h4 id={"process-automation"} className={"wp-block-heading has-small-font-size"}>{"Process automation"}</h4>
<p className={"wp-block-paragraph"}>{"I strived to make support processes faster and easier, so I tailored data extraction according to the problem described in a ticket. It also depends on the chosen board. Integrations with certain products empower process automation. This is based on the main AI-powered functions that the Forethought team delivered, of course."}</p>
</div>
</div>
</div>
<div id={""} className={"grid-item"}><div style={{"--pd": "24px", "--pm": "24px", "--phd": "24px", "--phm": "24px"}} className={"card-block img-top icn-top card-block--image wp-block-geniusee-card"}><figure className={"wp-block-image size-full card-image"}><img loading={"lazy"} decoding={"async"} width={"2480"} height={"1600"} src={"/assets/forethought/Picture-3-3.png"} alt={"Picture 3 3"} className={"wp-image-6111"} title={"Forethought: Enterprise AI agents for customer support 6"} />
</figure>
<div className={"wp-block-group card-content is-layout-flow wp-block-group-is-layout-flow"}><h4 id={"smart-notes"} className={"wp-block-heading has-small-font-size"}>{"Smart notes"}</h4>
<p className={"wp-block-paragraph"}>{"I developed a tool that allows support representatives to create work notes using a wide range of Forethought possibilities. End users (service agents) may create public and private notes and templates. Suggestions empowered by multiple variables are also presented."}</p>
</div>
</div>
</div>
<div id={""} className={"grid-item"}><div style={{"--pd": "24px", "--pm": "24px", "--phd": "24px", "--phm": "24px"}} className={"card-block img-top icn-top card-block--image wp-block-geniusee-card"}><figure className={"wp-block-image size-full card-image"}><img loading={"lazy"} decoding={"async"} width={"2480"} height={"1600"} src={"/assets/forethought/Picture-4-3.png"} alt={"Picture 4 3"} className={"wp-image-6113"} title={"Forethought: Enterprise AI agents for customer support 7"} />
</figure>
<div className={"wp-block-group card-content is-layout-flow wp-block-group-is-layout-flow"}><h4 id={"admin-analytics"} className={"wp-block-heading has-small-font-size"}>{"Admin analytics"}</h4>
<p className={"wp-block-paragraph"}>{"I tailored the analytical system in the admin panel. I delivered an interactive dashboard with the most necessary features and service reports. Admins (PMs, delivery managers, or any other responsible person in an organization) may check ticket quantity by agents and clients, amount of jobs done, and many more. This allows the use of all possibilities of AI for customer satisfaction and company profitability."}</p>
</div>
</div>
</div>
<div id={""} className={"grid-item"}><div style={{"--pd": "24px", "--pm": "24px", "--phd": "24px", "--phm": "24px"}} className={"card-block img-top icn-top card-block--image wp-block-geniusee-card"}><figure className={"wp-block-image size-full card-image"}><img loading={"lazy"} decoding={"async"} width={"2480"} height={"1600"} src={"/assets/forethought/Picture-5-1.png"} alt={"Picture 5 1"} className={"wp-image-6114"} title={"Forethought: Enterprise AI agents for customer support 8"} />
</figure>
<div className={"wp-block-group card-content is-layout-flow wp-block-group-is-layout-flow"}><h4 id={"autocomplete"} className={"wp-block-heading has-small-font-size"}><strong>{"Autocomplete"}</strong>
</h4>
<p className={"wp-block-paragraph"}>{"I enabled an AI-driven autocomplete feature that speeds up agent responses by generating contextual suggestions as they type. The system analyzes message content in real time, helping support teams respond faster and with higher accuracy."}</p>
</div>
</div>
</div>
</div>
</section>
<section className={"grid-wrapper"} style={{}}><div className={"block-header"}><div className={"heading-with-button"}><div className={"heading-with-button__inner"}><h2 id={"results"} className={"block-title"} data-target={"6"}>{" Results"}</h2>
</div>
</div>
<hr className={"block-header__separator"} />

</div>
<div id={""} className={"grid-block grid typo grid--columns-2"} style={{"--cols": "2", "--cgap": ".5rem", "--rgap": ".5rem"}}><div id={""} className={"grid-item"}><div style={{"--pd": "24px", "--pm": "24px", "--phd": "24px", "--phm": "24px"}} className={"card-block img-top icn-top is-style-default-card wp-block-geniusee-card"}><div style={{"--is": "24px"}} className={"icon-block icon-block--align-left wp-block-geniusee-icon"}>
<svg className={"icon-block__icon"} width={"24"} height={"24"}><use href={"/assets/Next.svg#icon"}></use>
</svg>
</div>
<p className={"has-large-font-size paragraph-margin-m wp-block-paragraph"}><strong>{"A unified Chrome extension adopted across multiple industries"}</strong>
</p>
<p className={"paragraph-margin-m wp-block-paragraph"}>{"The delivered extension is now used by support teams in e-commerce, FinTech, and SaaS, consolidating daily workflows into a single, AI-assisted workspace."}</p>
</div>
</div>
<div id={""} className={"grid-item"}><div style={{"--pd": "24px", "--pm": "24px", "--phd": "24px", "--phm": "24px"}} className={"card-block img-top icn-top is-style-default-card wp-block-geniusee-card"}><div style={{"--is": "24px"}} className={"icon-block icon-block--align-left wp-block-geniusee-icon"}>
<svg className={"icon-block__icon"} width={"24"} height={"24"}><use href={"/assets/optimization-shield.svg#icon"}></use>
</svg>
</div>
<p className={"has-large-font-size paragraph-margin-m wp-block-paragraph"}><strong>{"Seamless connectivity with major enterprise systems"}</strong>
</p>
<p className={"paragraph-margin-m wp-block-paragraph"}>{"The solution reliably integrates with widely used tools, frameworks, and internal platforms, ensuring consistent performance regardless of the tech stack."}</p>
</div>
</div>
<div id={""} className={"grid-item"}><div style={{"--pd": "24px", "--pm": "24px", "--phd": "24px", "--phm": "24px"}} className={"card-block img-top icn-top is-style-default-card wp-block-geniusee-card"}><div style={{"--is": "24px"}} className={"icon-block icon-block--align-left wp-block-geniusee-icon"}>
<svg className={"icon-block__icon"} width={"24"} height={"24"}><use href={"/assets/youtube-gaming.svg#icon"}></use>
</svg>
</div>
<p className={"has-large-font-size paragraph-margin-m wp-block-paragraph"}><strong>{"AI-driven productivity gains for support teams"}</strong>
</p>
<p className={"paragraph-margin-m wp-block-paragraph"}>{"Forethought’s Assist and Discover functions now surface real-time suggestions, insights, and task automation, enabling faster ticket resolution and improved agent efficiency."}</p>
</div>
</div>
</div>
</section>
</div>
</div>
</div>
</div>
</section>

 );
}
