import PersonalStats from './components/sections/PersonalStats';
import ContactPage from './pages/ContactPage';
import ProjectTestimonials from './components/sections/ProjectTestimonials';
import LevelsHealth from './pages/LevelsHealth';
import Projects from './pages/Projects';
import Header from './components/layout/Header';
import Hero from './components/sections/Hero';
import TrustedCompanies from './components/sections/TrustedCompanies';
import FeaturedProjects from './components/sections/FeaturedProjects';
import MoreProjects from './components/sections/MoreProjects';
import Services from './components/sections/Services';
import PersonalAbout from './components/sections/PersonalAbout';
import Certifications from './components/sections/Certifications';
import Industries from './components/sections/Industries';
import Contact from './components/sections/Contact';
import Footer from './components/layout/Footer';
import Background from './components/layout/Background';
import usePageInteractions from './hooks/usePageInteractions';
import MyTutor from './pages/MyTutor';
import AlvarezAndMarsal from './pages/AlvarezAndMarsal';
import ImagineAI from './pages/ImagineAI';
import Spicerhaart from './pages/Spicerhaart';
import XUnlocked from './pages/XUnlocked';
import Permio from './pages/Permio';
import Forethought from './pages/Forethought';
import Keep from './pages/Keep';
import Silibrain from './pages/Silibrain';
export default function App() {
 const path = window.location.pathname.replace(/\/$/, '');
 const isLevels = ['/projects/levels-health', '/projects/level-health', '/portfolio/geniusee/level-health'].includes(path);
 const isContact = path === '/contact';
 const isProjects = ['/projects', '/portfolio'].includes(path);
 const isMyTutor = ['/projects/my-tutor', '/portfolio/geniusee/my-tutor', '/my-tutor'].includes(path);
 const isAlvarez = ['/projects/alvarez-and-marsal', '/portfolio/geniusee/alvarez-and-marsal'].includes(path);
 const isImagine = ['/projects/imagine-ai', '/portfolio/geniusee/imagine-ai'].includes(path);
 const isSpicerhaart = ['/projects/spicerhaart', '/portfolio/geniusee/spicerhaart'].includes(path);
 const isXUnlocked = ['/projects/xunlocked', '/portfolio/geniusee/xunlocked'].includes(path);
 const isPermio = ['/projects/permio', '/portfolio/geniusee/permio'].includes(path);
 const isForethought = ['/projects/forethought', '/portfolio/geniusee/forethought'].includes(path);
 const isKeep = ['/projects/keep', '/portfolio/geniusee/keep'].includes(path);
 const isSilibrain = ['/projects/silibrain', '/portfolio/geniusee/silibrain'].includes(path);
 document.body.classList.toggle('home', !isContact && !isLevels && !isProjects && !isMyTutor && !isAlvarez && !isImagine && !isSpicerhaart && !isXUnlocked && !isPermio && !isForethought && !isKeep && !isSilibrain);
 document.body.classList.toggle('mytutor-page', isMyTutor);
 document.body.classList.toggle('single-case_study', isLevels || isMyTutor || isAlvarez || isImagine || isSpicerhaart || isXUnlocked || isPermio || isForethought || isKeep || isSilibrain);
 document.title = isContact ? 'Contact Dan | Full-Stack & AI Engineering' : isLevels ? 'Levels Health - a mobile app for tracking metabolic health' : isProjects ? 'Projects | Dan' : isSilibrain ? 'Silibrain: Digital transformation of healthcare systems' : isKeep ? 'Keep: FinTech-powered solution for employee retention' : isForethought ? 'Enterprise AI customer support integration for Forethought' : isPermio ? 'AI-driven permit automation for Service First Permits' : isXUnlocked ? 'xUnlocked multi-domain learning platform development' : isSpicerhaart ? 'Streamlining property video for estate agency brands' : isImagine ? 'Imagine AI: Accelerating hiring by up to 90%' : isAlvarez ? 'How I helped streamline enterprise logistics for A&M' : isMyTutor ? 'MyTutor online tutoring platform for schools' : 'Dan | Full-Stack Engineer & AI Developer';
 usePageInteractions();
 return <><Header/><main className="site-main">{isContact ? <ContactPage /> : isLevels ? <LevelsHealth /> : isProjects ? <Projects /> : isSilibrain ? <Silibrain /> : isKeep ? <Keep /> : isForethought ? <Forethought /> : isPermio ? <Permio /> : isXUnlocked ? <XUnlocked /> : isSpicerhaart ? <Spicerhaart /> : isImagine ? <ImagineAI /> : isAlvarez ? <AlvarezAndMarsal /> : isMyTutor ? <MyTutor /> : <><Hero/><PersonalStats/><PersonalAbout/><TrustedCompanies/><FeaturedProjects/><MoreProjects/><Services/><Certifications/><Industries/><ProjectTestimonials/><Contact/></>}</main><Footer/><Background/></>;
}
